version: '3.3'

services:
  nginx:
    image: nginx:stable
    container_name: realtime-nginx
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
      - ./static:/static
    depends_on:
      - backend
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    restart: always
    env_file:
      - .env
  db:
      image: postgres:12-alpine
      container_name: realtime-db
      volumes:
        - project_db:/var/lib/postgresql/data
      restart: always
      ports:
        - 5432:5432
      env_file:
        - .env
  backend:
      build: .
      command: >
        sh -c "
               python3 manage.py collectstatic --noinput &&
               python3 manage.py migrate --noinput &&
               python3 manage.py start_service &&
               python3 manage.py runserver 0.0.0.0:8000"
      container_name: realtime-backend
      env_file:
        - .env
      volumes:
        - ./app:/app
        - ./logs:/logs
        - ./static:/static
      ports:
        - 8000:8000
      restart: always
      depends_on:
        - db
volumes:
    project_db:
