# Generated by Django 3.2.10 on 2022-06-10 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cache',
            name='cache_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cache'),
        ),
        migrations.AddField(
            model_name='cache',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cache',
            name='tree_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
